# Generated by Django 4.1 on 2022-09-16 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_user_status_doctordetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctordetails',
            name='doctor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.user'),
        ),
    ]
