# Generated by Django 4.1 on 2022-09-16 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_doctordetails_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='doctor_details',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.doctordetails'),
        ),
        migrations.AlterField(
            model_name='doctordetails',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user'),
        ),
    ]
