# Generated by Django 4.1 on 2022-09-16 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_user_doctor_details_alter_doctordetails_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='doctor_details',
        ),
    ]
