# Generated by Django 4.1 on 2022-10-28 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='type',
            field=models.CharField(default='MEDICINE', max_length=50),
        ),
    ]
