# Generated by Django 4.1 on 2022-10-28 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_inventory_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
